package com.example.data.remote

import android.content.Context
import android.util.Log
import com.example.data.local.ModelRepository
import com.example.data.model.AgentPreset
import com.example.data.model.ChatMessage
import com.example.data.model.FileAttachment
import com.example.data.model.LocalModel
import com.example.data.model.LocalModels
import com.example.data.model.ResponseMode
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import net.amazingapps.llama.android.core.AiChat
import net.amazingapps.llama.android.core.InferenceEngine

/**
 * Real on-device AI.
 *
 * Every token returned by this class is generated by llama.cpp running the downloaded GGUF
 * weights on the device CPU. There are no canned answers, no templates and no scripted
 * fallbacks anywhere in this file: if the model cannot run we surface the actual error
 * instead of pretending to be an AI.
 */
class LocalAgentEngine(private val context: Context) {

    sealed interface EngineStatus {
        /** Weights are not on the device yet. */
        data object ModelMissing : EngineStatus

        /** Weights present, llama.cpp not yet initialised. */
        data object Idle : EngineStatus

        data object LoadingModel : EngineStatus

        /** Model loaded in RAM and ready to generate. */
        data object Ready : EngineStatus

        data object Generating : EngineStatus

        data class Error(val message: String) : EngineStatus
    }

    private val modelRepository = ModelRepository(context)

    private val _status = MutableStateFlow<EngineStatus>(EngineStatus.Idle)
    val status: StateFlow<EngineStatus> = _status.asStateFlow()

    /** llama.cpp is single-context; serialise everything that touches it. */
    private val engineMutex = Mutex()

    private var engine: InferenceEngine? = null
    private var loadedModelId: String? = null
    private var activeSystemPrompt: String? = null

    fun isModelAvailable(model: LocalModel = LocalModels.DEFAULT): Boolean =
        modelRepository.isDownloaded(model)

    fun refreshAvailability(model: LocalModel = LocalModels.DEFAULT) {
        if (!modelRepository.isDownloaded(model)) {
            _status.value = EngineStatus.ModelMissing
        } else if (_status.value is EngineStatus.ModelMissing) {
            _status.value = EngineStatus.Idle
        }
    }

    /**
     * Streams a genuine model response token by token.
     *
     * @throws InferenceUnavailableException when the weights are missing or llama.cpp cannot
     * load them — callers must show that error rather than substituting fake content.
     */
    fun generate(
        userMessage: String,
        history: List<ChatMessage>,
        attachments: List<FileAttachment>,
        agentPreset: AgentPreset,
        customInstruction: String,
        responseMode: ResponseMode,
        language: String,
        model: LocalModel = LocalModels.DEFAULT
    ): Flow<String> = flow {
        val systemPrompt = buildSystemPrompt(
            agentPreset = agentPreset,
            customInstruction = customInstruction,
            responseMode = responseMode,
            language = language
        )

        val prompt = buildConversationPrompt(
            userMessage = userMessage,
            history = history,
            attachments = attachments
        )

        engineMutex.withLock {
            val active = ensureModelLoaded(model, systemPrompt)
            _status.value = EngineStatus.Generating
            try {
                // Thinking mode needs headroom for the reasoning block plus the answer;
                // instant mode is capped shorter so replies land quickly on a phone CPU.
                val budget = when (responseMode) {
                    ResponseMode.THINKING -> THINKING_PREDICT_TOKENS
                    ResponseMode.INSTANT -> INSTANT_PREDICT_TOKENS
                }
                active.sendUserPrompt(prompt, predictLength = budget)
                    .collect { token -> emit(token) }
                _status.value = EngineStatus.Ready
            } catch (e: CancellationException) {
                _status.value = EngineStatus.Ready
                throw e
            } catch (e: Exception) {
                Log.e(TAG, "Inference failed", e)
                _status.value = EngineStatus.Error(e.message ?: "Inference failed")
                throw InferenceUnavailableException(
                    "The model failed while generating a response: ${e.message ?: "unknown error"}",
                    e
                )
            }
        }
    }.flowOn(Dispatchers.IO)

    /**
     * Loads the GGUF into llama.cpp if needed and applies the system prompt.
     * The library requires the system prompt to be set immediately after loading, so changing
     * the persona/language forces a reload.
     */
    private suspend fun ensureModelLoaded(
        model: LocalModel,
        systemPrompt: String
    ): InferenceEngine {
        if (!modelRepository.isDownloaded(model)) {
            _status.value = EngineStatus.ModelMissing
            throw InferenceUnavailableException(
                "${model.displayName} (${model.sizeLabel}) is not downloaded yet. " +
                    "Download it in Settings to start using the AI."
            )
        }

        val current = engine
        if (current != null &&
            loadedModelId == model.id &&
            activeSystemPrompt == systemPrompt
        ) {
            return current
        }

        // Persona or model changed: unload before reloading so the system prompt takes effect.
        if (current != null) {
            runCatching { current.cleanUp() }
                .onFailure { Log.w(TAG, "Unload before reload failed", it) }
        }

        _status.value = EngineStatus.LoadingModel
        val target = current ?: AiChat.getInferenceEngine(context)

        return try {
            target.loadModel(modelRepository.modelFile(model).absolutePath)
            target.setSystemPrompt(systemPrompt)
            engine = target
            loadedModelId = model.id
            activeSystemPrompt = systemPrompt
            _status.value = EngineStatus.Ready
            target
        } catch (e: Exception) {
            Log.e(TAG, "Failed to load model", e)
            engine = null
            loadedModelId = null
            activeSystemPrompt = null
            _status.value = EngineStatus.Error(e.message ?: "Could not load the model")
            throw InferenceUnavailableException(
                "Could not load ${model.displayName}: ${e.message ?: "unknown error"}",
                e
            )
        }
    }

    /** Releases the weights from RAM (e.g. when the user deletes the model). */
    suspend fun unload() = withContext(Dispatchers.IO) {
        engineMutex.withLock {
            engine?.let { active ->
                runCatching { active.cleanUp() }
                    .onFailure { Log.w(TAG, "cleanUp failed", it) }
            }
            loadedModelId = null
            activeSystemPrompt = null
            _status.value = EngineStatus.Idle
        }
    }

    private fun buildSystemPrompt(
        agentPreset: AgentPreset,
        customInstruction: String,
        responseMode: ResponseMode,
        language: String
    ): String = buildString {
        appendLine(agentPreset.systemPrompt)
        appendLine()
        if (language == "km") {
            appendLine(
                "LANGUAGE REQUIREMENT (MANDATORY): Answer in polite, natural, accurate Khmer " +
                    "(ភាសាខ្មែរ). Keep code, file paths and technical symbols inside Markdown code blocks."
            )
        } else {
            appendLine("LANGUAGE REQUIREMENT: Respond in clear, professional English using Markdown.")
        }
        if (customInstruction.isNotBlank()) {
            appendLine()
            appendLine("User custom instruction: $customInstruction")
        }
        appendLine()
        when (responseMode) {
            ResponseMode.THINKING -> appendLine(
                "REASONING MODE: Work through the problem step by step inside a " +
                    "<thought>...</thought> block first. Check your assumptions and consider " +
                    "edge cases there. After closing </thought>, give a clear final answer. " +
                    "Keep the thought block concise."
            )

            ResponseMode.INSTANT -> appendLine(
                "INSTANT MODE: Answer directly and concisely. Do NOT narrate your reasoning " +
                    "and do NOT emit a <thought> block. Lead with the answer."
            )
        }
    }.trim()

    /**
     * Flattens the recent conversation and any attachments into a single prompt.
     * The engine keeps its own KV cache, but replaying recent turns keeps context coherent
     * after a persona/model reload.
     */
    private fun buildConversationPrompt(
        userMessage: String,
        history: List<ChatMessage>,
        attachments: List<FileAttachment>
    ): String = buildString {
        val recent = history
            .filter { it.content.isNotBlank() }
            .takeLast(HISTORY_TURNS)

        if (recent.isNotEmpty()) {
            appendLine("Conversation so far:")
            recent.forEach { msg ->
                val who = if (msg.role == "user") "User" else "Assistant"
                appendLine("$who: ${msg.content.take(MAX_HISTORY_CHARS)}")
            }
            appendLine()
        }

        val attachmentContext = buildAttachmentContext(attachments)
        if (attachmentContext.isNotBlank()) {
            appendLine("--- ATTACHED FILES ---")
            appendLine(attachmentContext)
            appendLine("--- END OF ATTACHMENTS ---")
            appendLine()
        }

        append(userMessage.ifBlank { "Analyse the attached files and summarise what they contain." })
    }.trim()

    private fun buildAttachmentContext(attachments: List<FileAttachment>): String {
        if (attachments.isEmpty()) return ""
        return buildString {
            attachments.forEachIndexed { index, file ->
                appendLine("[Attachment ${index + 1}: ${file.name} (${file.sizeFormatted})]")
                if (file.isZip) {
                    appendLine("ZIP archive with ${file.entryCount} entries.")
                    appendLine(file.contentSummary.take(MAX_ATTACHMENT_CHARS))
                } else {
                    appendLine("Type: ${file.mimeType}")
                }
                if (file.textPreview.isNotBlank()) {
                    appendLine("Content preview:")
                    appendLine(file.textPreview.take(MAX_ATTACHMENT_CHARS))
                }
                appendLine()
            }
        }
    }

    private companion object {
        const val TAG = "LocalAgentEngine"
        const val INSTANT_PREDICT_TOKENS = 512
        const val THINKING_PREDICT_TOKENS = 1536
        const val HISTORY_TURNS = 6
        const val MAX_HISTORY_CHARS = 1200
        const val MAX_ATTACHMENT_CHARS = 4000
    }
}

/**
 * Raised when a genuine model response cannot be produced. The UI surfaces this verbatim —
 * we never replace a failure with fabricated "AI" text.
 */
class InferenceUnavailableException(
    message: String,
    cause: Throwable? = null
) : Exception(message, cause)
